config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pictures#index'
  resources :pictures do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :picture
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :likes
  belongs_to :user
  has_attached_file :image,
  styles: { medium: "300x300>", thumb: "100x100>" }

  validates :image, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pictures, dependent: :destroy
  has_many :comments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @picture = Picture.find(params[:picture_id])
    @comment = Comment.new
  end

  def create
    @picture = Picture.find(params[:picture_id])
    @picture.comments.create(comment_params)
    redirect_to picture_path(@picture)
  end

  private

  def comment_params
    params.require(:comment).permit(:thoughts)
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @pictures = Picture.all
    @current_user = current_user
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.create(picture_params)
    redirect_to '/pictures'
  end

  def show
    @picture = Picture.find(params[:id])
    @current_user = current_user
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    flash[:notice] = 'Picture deleted successfully'
    redirect_to '/pictures'
  end

  private

  def picture_params
    params.require(:picture).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/comments/new.html.erb
<%= form_for [@picture, @comment] do |f| %>
  <%= f.label :Comment %>
  <%= f.text_area :thoughts %>
  <%= f.submit 'Post Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice %>
<%= alert %>
<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>
<%= yield %>

</body>
</html>

app/views/pictures/index.html.erb
<% if @current_user %>
<a href="/pictures/new">Add a picture</a>
<% end %>

<br>
<% if @pictures.any? %>
  <% @pictures.each do |picture| %>
    <%= link_to image_tag(picture.image.url(:thumb)), picture_path(picture) %>
  <% end %>
<% else %>
  <p>No pictures yet</p>
<% end %>

app/views/pictures/new.html.erb
<%= form_for @picture, html: {multipart: true} do |f| %>
  <%= f.label :upload_a_picture %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/pictures/show.html.erb
<%= image_tag @picture.image.url %>
<% if @current_user %>
  <%= link_to "Delete this picture", picture_path(@picture), method: :delete %>
  <%= link_to "Comment on this picture", new_picture_comment_path(@picture) %>
<% end %>
<% if @picture.comments.any? %>
  <% @picture.comments.each do |comment| %>
    <%= comment.thoughts %>
    <% comment.user %>
  <% end %>
<% end %>